# Generated by Django 6.0.6 on 2026-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
